/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_H_RPCGEN
#define _LOG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LOGPROG 99
#define LOGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_LOG 1
extern  int * print_log_1(char *, CLIENT *);
extern  int * print_log_1_svc(char *, struct svc_req *);
extern int logprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_LOG 1
extern  int * print_log_1();
extern  int * print_log_1_svc();
extern int logprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_H_RPCGEN */
